### ISSUE TITLE
자가진단 보안 강화에 대해서

### ISSUE THREAD

**Issue by haechan07** [331leo/hcskr_python#19]
{'error': True, 'code': 'PASSWORD', 'message': '학생정보는 검색하였으나, 비밀번호가 틀립니다.'}가 리턴됐습니다.
비밀번호는 확인한 결과 맞으며, 자가진단 보안 강화에 대한 패치가 부족한 것인지 파악해주시면 좋겠습니다.
파이썬 버전 3.9.4

**Comment by 331leo** [comment]
제가 확인한 결과,
정상적으로 비밀번호를 입력한 경우 잘 작동하였습니다
hcskr 버전이 1.11.0 이상인지 다시 한번 확인해 주시고,
비밀번호를 5회 이상 틀려 IP ratelimit 걸리지 않았는지 확인 부탁드립니다.

**Comment by haechan07** [comment]
hcskr 버전은 1.11.1로 보입니다
IDLE을 사용했으며 비밀번호는 2번째 시도부터 맞았으나, 오늘 오전 8시에 재시도해보겠습니다.

**Comment by yng-min** [comment]
저도 똑같은 증상이 나타납니다.

**Comment by chlee7139** [comment]
저도 똑같은 증상이 나타납니다.

**Comment by 331leo** [comment]
음.. 저한태는 발생하지 않는 현상이라
가능하시다면 "학생 건강상태 자가진단" 어플리케이션에서는 정상적으로 작동하는지 확인 부탁드립니다.

**Comment by yng-min** [comment]
hcskr 모듈을 이용해서는 5번 가량 테스트해 보았지만 모두 실패하였고, 어플리케이션과 사이트에서는 정상적인 것을 확인하였습니다.

**Comment by haechan07** [comment]
저도 사이트에서는 작동합니다.
자가진단 앱은 사용하지 않습니다.

**Comment by 331leo** [comment]
해당 문제 확인하였습니다.
hcskr 라이브러리의 영향인지는 모르겠지만,
자가진단 서비스의 비밀번호 검증 방식이 약간 바뀐것 같습니다.
확인해보겠습니다

**Comment by zeroday0619** [comment]
클로즈드 소스로 변경하시는 걸 권장합니다.

**Comment by zeroday0619** [comment]
이거 또 뭐 건드린 듯 하네요
var initTime='';var limitTime=1;var useSession=false;var useSpace=true;var useGenKey=false;var useTalkBack=true;var java_ver=1.8;
