### ISSUE TITLE
사용자 정보가 올바름에도 불구하고 로그인 오류가 발생하는 증상

### ISSUE THREAD

**Issue by im-gugogi** [331leo/hcskr_python#21]
#특정 상황 또는 특정 학생으로 자가진단을 실행하는 경우 로그인 정보가 올바름에도 불구하고
{'error': True, 'code': 'PASSWORD', 'message': '학생정보는 검색하였으나, 비밀번호가 틀립니다.'}
를 반환하고 있습니다.

모바일 기기 또는 hcs.eduro.go.kr에서 수동으로 로그인하는 경우 정상적으로 로그인 가능합니다.

코드를 한번 실행할 때마다 failCnt 값이 증가하고 있는 것을 보면, 보안 키패드로 인한 로그인 불가 현상으로 추측됩니다.
이번 사이트 개편은 보안 키보드만 추가된 것이 아니라, 특정 상황에서 비밀번호를 한번 더 입력하여야 하는 등의 보안요소가 추가된 것으로 보입니다.

해당 현상이 본인의 학생 정보에서 재현되지 않거나, 기타 사유로 위 오류를 재현할 수 없는 경우 admin@gugogi.com 으로 메일을 남겨주시거나 코멘트로 메일 주소를 남겨주시면 해당 현상이 발생하는 학생 정보를 전송드리겠습니다.

**Comment by 331leo** [comment]
저의 경우, 해당오류가 재현되지 않습니다.
[me@leok.kr](mailto:me@leok.kr) 로 상세한 상황을 제공해주시면 확인해보겠습니다.
감사합니다 :+1:
