### ISSUE TITLE
validdatePassword에서 간헐적 학생정보 인증 오류 발생

### ISSUE THREAD

**Issue by RRT3333** [331leo/hcskr_python#28]
안녕하세요 

validdatePassword에서 간헐적으로 학생정보 인증 오류가 발생하며, 특정 패스워드에서 에러 빈도가 높은 것을 발견하였습니다.

1. 학생 패스워드 인증 시도시 간헐적(30회 시도중 1회 정도의 빈도)으로 다음과 같은 에러가 발생합니다. 
 ```
MESSAGE: UNKNOWN validatePassword: 알 수 없는 에러 발생. string argument should  contain only ASCII characters
```
> password에 상관 없이 불규칙적으로 발생합니다.

2.  password가 4로 시작하는 경우 추가적으로 다음과 같은 에러도 발생합니다.
```
MESSAGE: UNKNOWN validatePassword: 알 수 없는 에러 발생. '4' is not in list
```
> '4'외의 다른 숫자로 시작하는 password에서 같은 형식의 에러는 관측되지 않았습니다.

실행 환경은 다음과 같습니다.
`python3.8` `hcskr 1.13.0` `ubuntu 20.04.2`

**Comment by penggin** [comment]
자가진단 서버 불안정으로 인한 일시적인 오류였던것으로 추정됩니다. 현재는 해당 오류가 발생하지 않습니다.

**Comment by RRT3333** [comment]
접속량 몰리는 시간은 피하고 있기는 한데...
일단 며칠 경과 지켜보도록 해보겠습니다

**Comment by 331leo** [comment]
#27
