### ISSUE TITLE
자가진단 사이트 구조 변경

### ISSUE THREAD

**Issue by hyunwoo3235** [331leo/hcskr_python#6]
방금 확인 결과 사이트가 또 바뀌었습니다

기존에 validatePassword에서는 단순히 비밀번호가 맞다면 'true', 아니면 에러 코드를 반환했지만

이제는 맞다면 또다른 토큰을 반환하여 이걸로 다음 과정을 거쳐야 합니다.

따라서 비밀번호 또한 인자로 입력받아야 할 것 같습니다.

**Comment by 331leo** [comment]
아이고... 알겠습니다..
